### ISSUE TITLE
[BUG] Cellfinder cell viewer - point size

### ISSUE THREAD

**Issue by chrytsi** [brainglobe/cellfinder#103]
**Describe the bug**
Changing the point size in Cellfinder cell viewer only affects points that are subsequently added.

**Expected behavior**
I would have expected the point size to change for all points that already exist in a given category (i.e. Cells / Non-Cells), and for the ones that are subsequently added. This would make inspection of cells/candidates easier as they are - depending on cell size - mostly covered by the symbol indicating the point location.

**Desktop (please complete the following information):**
 - OS: Windows 7

**Comment by adamltyson** [comment]
Yep, this need to be fixed. In the mean time you should be able to pass e.g `--marker-size 25` to set the size of the points when starting the viewer.

**Comment by adamltyson** [comment]
N.B. You can also select cells, and then change the size of those specifically.

**Comment by chrytsi** [comment]
update: same goes for changing the symbols' colour.
changing the opacity and symbol works fine.

**Comment by rdbcasillas** [comment]
Hi @adamltyson, Is it possible to select *all* the cells after loading a cellfinder output folder in cellfinder viewer?  Currently, I can only select the cells that are in a particular plane (layer) which limits the actions I want to generalize to all the cells (like changing color) irrespective of the plane. When I move the left to right, new cells appear with the old defaults which makes the analysis cumbersome and redundant sometimes.

I would also love to export each and every layer as a separate TIFF file so that my changes made in a layer can be exported (color, size of points etc). Is that possible? Write now, I can only "save all layers" as a single TIFF file (which is huge usually).  

Thank you!

**Comment by adamltyson** [comment]
Hi @rdbcasillas, I actually don't know the answer to either of your questions. The viewer is just a plugin for [napari](https://github.com/napari/napari), so someone in napari-land might know the answer, or if there's an existing issue/PR.

@sofroniewn might know (sorry for bugging you whenever there's a napari question), does napari have the functionality to select all points (in ND), or to export what are essentially screenshots of a single plane?

**Comment by sofroniewn** [comment]
> @sofroniewn might know (sorry for bugging you whenever there's a napari question), does napari have the functionality to select all points (in ND)

No worries. You should be able to select all the points with
```python
layer.selected_data = list(range(len(layer.data)))
```
from the CLI (but bug reports welcome if that is not functioning as expected). If I understand right is the request maybe to be able to do that from the GUI too? we could make a modified version of the `a` key press do that.

> I would also love to export each and every layer as a separate TIFF file so that my changes made in a layer can be exported (color, size of points etc). Is that possible? Write now, I can only "save all layers" as a single TIFF file (which is huge usually).
>
> or to export what are essentially screenshots of a single plane?

If you do save all layers and have 3 image layers you should be able to get a folder with 3 tiffs. If you have one layer with many timepoints we don't have a quick an easy way to get one tif per time point, but it should be pretty easy to write a custom writer plugin for that

**Comment by adamltyson** [comment]
Thanks @sofroniewn!


>  If I understand right is the request maybe to be able to do that from the GUI too? we could make a modified version of the a key press do that.

Yep, it would be great it that was possible. From my POV, it should be the default, but it might not work for everyone.

> but it should be pretty easy to write a custom writer plugin for that

I haven't written a writer plugin, but I can give it a go. @rdbcasillas, would you be able to raise a new issue, detailing exactly what you'd like to save and how (maybe with screenshots etc.), and I can look into it. This might be useful for quite a few people.

**Comment by rdbcasillas** [comment]
Thank you @adamltyson for looking into this! And thanks @sofroniewn for explaining how to do this via CLI! 

>would you be able to raise a new issue, detailing exactly what you'd like to save and how (maybe with screenshots etc.)

@adamltyson Should I create a new bug or a new feature request for this? 

Also, I notice that there is a repository napari-cellfinder. How are the instructions mentioned there different from  cellfinder_view? Are there any advantages of using one over the other? I tried those instructions but when I drag and drop cellfinder output folder, I get an error saying folder wasn't recognized. But of course same folder works very well with cellfinder_view. (sorry for mentioning this here, i can open new issue for this too in napari-cellfinder rep)

**Comment by adamltyson** [comment]
>Should I create a new bug or a new feature request for this?

Feature, but it doesn't really matter.

Re `napari-cellfinder` vs `cellfinder_view` - In cellfinder version 0.4x, `cellfinder_view` has been replaced with the `napari-cellfinder` plugin. This is easier to use, and easier to maintain, but at the expense of slightly reduced functionality (that will be improved in time).

If you update cellfinder, the output file structure will have changed, and it will then work with the napari cellfinder plugin. If the new tool doesn't do what you need it to, let me know.

**Comment by adamltyson** [comment]
@rdbcasillas, release notes for version 0.4.x [here](https://docs.brainglobe.info/cellfinder/release-notes#version-0-4-0-2020-10-13) and updated instructions [here](https://docs.brainglobe.info/cellfinder/user-guide). You're of course welcome to keep using version 0.3, as there have been some relatively major changes in version 0.4.

**Comment by rdbcasillas** [comment]
@adamltyson  Nice! And wow, that's quite a lot of changes. Will test it for sure.  I was wondering about the brainglobe suite and felt this was a very nice idea. Congrats on the new version! \0/

**Comment by adamltyson** [comment]
Closing this, as it's referring to long-deprecated code. Ideally this functionality would be added into napari, but feel free to raise issues in either [cellfinder-napari](https://github.com/brainglobe/cellfinder-napari) or [brainglobe-napari-io](https://github.com/brainglobe/brainglobe-napari-io) (if it's just for visualisation of saved results).
