### ISSUE TITLE
[Docs] An example showing how to use amap's registration output with cellfinder's cell detection.

### ISSUE THREAD

**Issue by rdbcasillas** [brainglobe/cellfinder#118]
**If there is an issue with the documentation, where is it? E.g. website, 
README? If this is a suggestion, where should it go?**
Website

**What is the issue?**
Not sure how to use the registration output of amap for subsequent cell detection with cellfinder. [Data Requirements](https://docs.cellfinder.info/user-guide/data-requirements)  page says that for registration we ideally use the "background channel". So after doing that, how do we proceed with cell detection? Since both "-s" and "-b" flags take input as "series of 2d tiff" files, it is not clear how to use amap's registration output  (for background channel). 

**How could this be improved?**
By providing a short end to end tutorial of using both amap and cellfinder for a specific background and signal channels. Ideally it should be reproducible and example image files provided as part of the package.

**Comment by adamltyson** [comment]
Hi,

> Not sure how to use the registration output of amap for subsequent cell detection with cellfinder.

Yep, the docs aren't clear here, I should update them. For your reference, you have two options:
* The easiest is probably just to register the data again. If you run cellfinder as per the docs [here](https://docs.cellfinder.info/user-guide/usage), but you use the `--register` flag, then cellfinder will use amap to register the data, and store the results in a way that cellfinder will "understand". If you use any other flag that would require registration (such as `--summarise`) then registration will be run too. In future, running the registration will be the default option (see https://github.com/SainsburyWellcomeCentre/cellfinder/issues/63).
* If you don't want to run the registration again, you can "trick" cellfinder into thinking it has already been run:
    * Create a cellfinder output directory (just an empty directory)
    * Copy your amap output directory into the cellfinder directory, and rename it `registration`.
    * Run cellfinder with the `--register` (or `--summarise` etc.) flag, and it should read that registration has already been performed, and skip it.

I'm aware that it would be nice to just supply your directory (e.g. `cellfinder -s signal_image --amap-dir /path/to/amap_out`). The reason that this is not an option is that some downstream tools rely on the cellfinder output directory structure being fixed (and the registration not being elsewhere). To maintain this behavior (and to allow the cellfinder output directory to be portable), the whole amap directory would need to be copied as part of cellfinder anyway (and users may not be aware how much disk space this would need). For now at least, I'm leaving the user to copy the directory themselves. If this causes issues in anyway, then automated copying could be introduced.

The other reason why you always need to supply the background channel is that it is a key part of the cell detection process. Although it should be possible to make this optional in the future (see https://github.com/SainsburyWellcomeCentre/cellfinder/issues/119).


>  By providing a short end to end tutorial of using both amap and cellfinder for a specific background and signal channels. Ideally it should be reproducible and example image files provided as part of the package.

This is a priority (see https://github.com/SainsburyWellcomeCentre/cellfinder/issues/56), but for now, cellfinder is changing quite a lot, and so a full step by step tutorial will probably come once the usage has stabilised a bit more. However, if you or anyone else has used cellfinder successfully, I'd be happy to accept any contributions.

**Comment by rdbcasillas** [comment]
Thanks @adamltyson for detailed response. Copying amap directory and renaming it worked for cell detection but classification could not happen because the dimensions didn't match completely between the signal and the background (2000 * 1194 vs 2000 * 1180). 


This brings me to another question. I have seen that if my image is 2000 * 1194 * 480 (pixel units), my registration works even if I use -x 10 -y 10 -z 10. Maybe it works but the output is going to be wrong?  So I am a little confused about the voxel units that cellfinder and amap expect. 

It would be nice if we can have a small example of converting pixel units into units that cellfinder expects because right now it seems like if the conversion isn't exact, it still runs without any particular error or warning about it. Is it autocorrecting the conversion?

**Comment by adamltyson** [comment]
>  the dimensions didn't match completely between the signal and the background (2000 * 1194 vs 2000 * 1180).

Sorry, yes the background and signal channels must (currently) be perfectly aligned, without this the classification doesn't work.

> my registration works even if I use -x 10 -y 10 -z 10.

The registration will run regardless of the voxel sizes you enter (although it could run out of memory), but the results may not be correct. Is the documentation [here](https://docs.cellfinder.info/user-guide/usage/specifying-pixel-size) not specific enough? If so, could you raise an issue detailing what's wrong? 

To clarify, both amap & cellfinder expect the voxel sizes to be input as microns. So if your voxel sizes are 2um in x & y, and 5um in z, then you would use `-x 2 -y 2 -z 5`.  By using `-x 10 -y 10 -z 10`, you're specifying that your voxels are 10um isotropic, and your image is approximately 20x12x5 mm.

**Comment by adamltyson** [comment]
There is now an [example of cell detection and registration in cellfinder](https://docs.brainglobe.info/cellfinder/tutorial) (still a work in progress).
