### ISSUE TITLE
[BUG]Registering failed

### ISSUE THREAD

**Issue by cindy12-gao** [brainglobe/cellfinder#144]
**Describe the bug**
INFO:root:Registering
2020-10-12 11:13:48 AM - INFO - MainProcess run.py:56 - Registering
INFO:root:Starting affine registration
2020-10-12 11:13:48 AM - INFO - MainProcess run.py:76 - Starting affine registration
Traceback (most recent call last):
  File "c:\users\cibr-imfacility-ws2\anaconda3\envs\cellfinder\lib\site-packages\imlib\general\system.py", line 282, in safe_execute_command
    cmd, stdout=log_file, stderr=error_file, shell=True
  File "c:\users\cibr-imfacility-ws2\anaconda3\envs\cellfinder\lib\subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'c:\users\cibr-imfacility-ws2\anaconda3\envs\cellfinder\lib\site-packages\brainreg\bin\nifty_reg\win64\reg_aladin -ln 6 -lp 5 -flo H:\output\niftyreg\brain_filtered.nii -ref H:\output\niftyreg\downsampled_filtered.nii -aff H:\output\niftyreg\affine_matrix.txt -res H:\output\niftyreg\affine_registered_atlas_brain.nii -omp 18' returned non-zero exit status 1.

**To Reproduce**
I test brainreg using the downloaded test data, but there always occurred error
order:brainreg H:\test_brain H:\output -v 50 40 40 --orientation asl --atlas allen_mouse_25um --n-free-cpus 30

**Expected behavior**

**Log file**
Please attach the cellfinder log file (e.g. `output/cellfinder_2019-12-17_13-29-46.log`)

**Screenshots**
brainreg H:\test_brain H:\output -v 50 40 40 --orientation asl --atlas allen_mouse_25um --n-free-cpus 30

H:\test_brain
(cellfinder) C:\Users\CIBR-ImFacility-WS2>brainreg H:\test_brain H:\output -v 50 40 40 --orientation asl --atlas allen_mouse_25um --n-free-cpus 30
INFO:root:Starting logging
2020-10-12 11:13:00 AM - INFO - MainProcess fancylog.py:279 - Starting logging
INFO:root:Not logging multiple processes
2020-10-12 11:13:00 AM - INFO - MainProcess fancylog.py:280 - Not logging multiple processes
INFO:root:Starting registration
2020-10-12 11:13:00 AM - INFO - MainProcess cli.py:191 - Starting registration
allen mouse atlas (res. 25um)
From: http://www.brain-map.org (Wang et al 2020, https://doi.org/10.1016/j.cell.2020.04.007 )
DEBUG:root:Determining the maximum number of CPU cores to use
DEBUG:root:Number of CPU cores available is: 18
DEBUG:root:Setting number of processes to: 18
INFO:root:Loading raw image data
2020-10-12 11:13:04 AM - INFO - MainProcess main.py:48 - Loading raw image data
DEBUG:root:Data type is: directory of files
DEBUG:root:Determining the maximum number of CPU cores to use
DEBUG:root:Number of CPU cores available is: 18
DEBUG:root:Setting number of processes to: 18
Loading images: 100%|█████████████████████████████████████████████████████████| 15/15 [00:00<00:00, 88.59plane/s]
Loading images: 100%|█████████████████████████████████████████████████████████| 15/15 [00:00<00:00, 88.59plane/s]
Loading images: 100%|█████████████████████████████████████████████████████████| 15/15 [00:00<00:00, 81.10plane/s]
Loading images: 100%|█████████████████████████████████████████████████████████| 15/15 [00:00<00:00, 81.10plane/s]

Loading images: 100%|█████████████████████████████████████████████████████████| 15/15 [00:00<00:00, 88.58plane/s]
Loading images: 100%|█████████████████████████████████████████████████████████| 15/15 [00:00<00:00, 88.58plane/s]
Loading images: 100%|█████████████████████████████████████████████████████████| 15/15 [00:00<00:00, 81.10plane/s]

Loading images: 100%|█████████████████████████████████████████████████████████| 15/15 [00:00<00:00, 81.10plane/s]
Loading images: 100%|█████████████████████████████████████████████████████████| 15/15 [00:00<00:00, 74.78plane/s]
Loading images: 100%|█████████████████████████████████████████████████████████| 15/15 [00:00<00:00, 88.58plane/s]
Loading images: 100%|█████████████████████████████████████████████████████████| 15/15 [00:00<00:00, 88.58plane/s]
Loading images: 100%|█████████████████████████████████████████████████████████| 15/15 [00:00<00:00, 88.58plane/s]
Loading images: 100%|█████████████████████████████████████████████████████████| 15/15 [00:00<00:00, 74.78plane/s]

Loading images: 100%|█████████████████████████████████████████████████████████| 15/15 [00:00<00:00, 81.10plane/s]
filtering: 100%|████████████████████████████████████████████████████████████| 456/456 [00:13<00:00, 34.79plane/s]
filtering: 100%|████████████████████████████████████████████████████████████| 434/434 [00:16<00:00, 25.60plane/s]
INFO:root:Registering
2020-10-12 11:13:48 AM - INFO - MainProcess run.py:56 - Registering
INFO:root:Starting affine registration
2020-10-12 11:13:48 AM - INFO - MainProcess run.py:76 - Starting affine registration
Traceback (most recent call last):
  File "c:\users\cibr-imfacility-ws2\anaconda3\envs\cellfinder\lib\site-packages\imlib\general\system.py", line 282, in safe_execute_command
    cmd, stdout=log_file, stderr=error_file, shell=True
  File "c:\users\cibr-imfacility-ws2\anaconda3\envs\cellfinder\lib\subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'c:\users\cibr-imfacility-ws2\anaconda3\envs\cellfinder\lib\site-packages\brainreg\bin\nifty_reg\win64\reg_aladin -ln 6 -lp 5 -flo H:\output\niftyreg\brain_filtered.nii -ref H:\output\niftyreg\downsampled_filtered.nii -aff H:\output\niftyreg\affine_matrix.txt -res H:\output\niftyreg\affine_registered_atlas_brain.nii -omp 18' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\cibr-imfacility-ws2\anaconda3\envs\cellfinder\lib\site-packages\brainreg\backend\niftyreg\registration.py", line 70, in register_affine
    self.paths.affine_error_path,
  File "c:\users\cibr-imfacility-ws2\anaconda3\envs\cellfinder\lib\site-packages\imlib\general\system.py", line 307, in safe_execute_command
    cmd,
imlib.general.system.SafeExecuteCommandError:
-------------------------
Process failed:
 The system cannot find the path specified.
-------------------------

-------------------------
please read the logs at H:\output\niftyreg\affine.log and H:\output\niftyreg\affine.err
-------------------------
command: c:\users\cibr-imfacility-ws2\anaconda3\envs\cellfinder\lib\site-packages\brainreg\bin\nifty_reg\win64\reg_aladin -ln 6 -lp 5 -flo H:\output\niftyreg\brain_filtered.nii -ref H:\output\niftyreg\downsampled_filtered.nii -aff H:\output\niftyreg\affine_matrix.txt -res H:\output\niftyreg\affine_registered_atlas_brain.nii -omp 18
-------------------------

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\cibr-imfacility-ws2\anaconda3\envs\cellfinder\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\cibr-imfacility-ws2\anaconda3\envs\cellfinder\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\CIBR-ImFacility-WS2\Anaconda3\envs\cellfinder\Scripts\brainreg.exe\__main__.py", line 7, in <module>
  File "c:\users\cibr-imfacility-ws2\anaconda3\envs\cellfinder\lib\site-packages\brainreg\cli.py", line 204, in main
    debug=args.debug,
  File "c:\users\cibr-imfacility-ws2\anaconda3\envs\cellfinder\lib\site-packages\brainreg\main.py", line 79, in main
    debug=debug,
  File "c:\users\cibr-imfacility-ws2\anaconda3\envs\cellfinder\lib\site-packages\brainreg\backend\niftyreg\run.py", line 77, in run_niftyreg
    brain_reg.register_affine()
  File "c:\users\cibr-imfacility-ws2\anaconda3\envs\cellfinder\lib\site-packages\brainreg\backend\niftyreg\registration.py", line 74, in register_affine
    "Affine registration failed; {}".format(err)
imlib.general.exceptions.RegistrationError: Affine registration failed;
-------------------------
Process failed:
 The system cannot find the path specified.
-------------------------

-------------------------
please read the logs at H:\output\niftyreg\affine.log and H:\output\niftyreg\affine.err
-------------------------
command: c:\users\cibr-imfacility-ws2\anaconda3\envs\cellfinder\lib\site-packages\brainreg\bin\nifty_reg\win64\reg_aladin -ln 6 -lp 5 -flo H:\output\niftyreg\brain_filtered.nii -ref H:\output\niftyreg\downsampled_filtered.nii -aff H:\output\niftyreg\affine_matrix.txt -res H:\output\niftyreg\affine_registered_atlas_brain.nii -omp 18
-------------------------

**Desktop (please complete the following information):**
OS: Windows 10 pro
hardware space:640GB RAM, Xeon 6136 CPU

**Additional context**
@adamltyson

**Comment by adamltyson** [comment]
Hi, @cindy12-gao, could you attach the log file? It should be saved in the output directory.

In the mean time would you mind:
* Creating a new conda environment
* Installing a fresh copy of brainreg (`pip install brainreg==0.2.0 --no-cache`)
* Rerunning the registration command, but saving into a new output directory.

**Comment by adamltyson** [comment]
Actually, I think I've found the problem. Aiming to get a fixed version released today.

**Comment by adamltyson** [comment]
This should be fixed now, can you update brainreg (`pip install brainreg -U`) and try the tutorial registration again?

**Comment by adamltyson** [comment]
@cindy12-gao Please note there was a typo in the brainreg tutorial command, it should be:
```
 brainreg test_brain brainreg_output -v 50 40 40  --orientation psl --atlas allen_mouse_50um
```

**Comment by cindy12-gao** [comment]
Thank you for your answer. I`ve update the brainreg –U and tested the test data and my own data, the registered results is perfect!


------------------------------------------------------------------
发件人：Adam Tyson <notifications@github.com>
发送时间：2020年10月12日(星期一) 23:42
收件人：brainglobe/cellfinder <cellfinder@noreply.github.com>
抄　送：高辛未 <gaoxinwei@cibr.ac.cn>; Mention <mention@noreply.github.com>
主　题：Re: [brainglobe/cellfinder] [BUG]Registering failed (#144)

@cindy12-gao Please note there was a typo in the brainreg tutorial command, it should be:
 brainreg test_brain brainreg_output -v 50 40 40  --orientation psl --atlas allen_mouse_50um

**Comment by adamltyson** [comment]
Great! Get in touch if you have any more problems.
