### ISSUE TITLE
[BUG] cellfinder_curate does not extract cubes

### ISSUE THREAD

**Issue by cindy12-gao** [brainglobe/cellfinder#150]
**Describe the bug**
Cells&non cells folders can be created, but the folders are empty 

**To Reproduce**
I use the demo data signal&background to only test the order cell-detection, and then cell.xml can be created.
after that, i ran the order like that cellfinder_curate and narapi opened, and i select some objects and no-signal objects from detected cells. then quit the narapi, cell and non-cell can be created, but nothing in there.
**Expected behavior**
cellfinder) C:\Users\CIBR-ImFacility-WS2>cellfinder_curate K:\cellfinder_master\cellfinder_master\tests\data\signal K:\cellfinder_master\cellfinder_master\tests\data\background H:\cellfinder_data_test\output\points\cells.xml -v 5 2 2
c:\users\cibr-imfacility-ws2\anaconda3\envs\cellfinder\lib\site-packages\qtpy\__init__.py:216: RuntimeWarning: Selected binding "pyqt5" could not be found, using "pyside2"
  'using "{}"'.format(initial_api, API), RuntimeWarning)
No output directory given, so setting output directory to: H:\cellfinder_data_test\output\points
8 points toggled and added to the list
8 points toggled and added to the list
4 points confirmed and added to the list
1 points toggled and added to the list
1 points toggled and added to the list
1 points toggled and added to the list
1 points toggled and added to the list
1 points toggled and added to the list
1 points toggled and added to the list
1 points toggled and added to the list
1 points toggled and added to the list
1 points toggled and added to the list
1 points confirmed and added to the list
1 points toggled and added to the list
1 points toggled and added to the list
1 points toggled and added to the list
1 points toggled and added to the list
1 points toggled and added to the list
1 points toggled and added to the list
Saving results to: H:\cellfinder_data_test\output\points\curated_cells.xml
Done!
Saving cubes to: H:\cellfinder_data_test\output\points
Extracting type: cells
Saving to: H:\cellfinder_data_test\output\points\cells
Thread: 11: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 14/14 [00:00<00:00, 297.87it/s]

Thread: 6: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 19/19 [00:00<00:00, 306.45it/s]

Thread: 9: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 307.70it/s]
Thread: 19:   0%|                                                                                                                                                    | 0/6 [00:00<?, ?it/s]
Thread: 16: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:00<00:00, 272.74it/s]
Thread: 19: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 260.84it/s]
Thread: 21: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 266.67it/s]
Thread: 23: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 200.04it/s]

Thread: 3:  95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████       | 19/20 [00:00<00:00, 131.03it/s]
Thread: 15: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 277.80it/s]
Thread: 14: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11/11 [00:00<00:00, 289.49it/s]
Thread: 10: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:00<00:00, 267.87it/s]

Thread: 18: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 279.96it/s]
Thread: 7: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 18/18 [00:00<00:00, 299.99it/s]
Thread: 20: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 277.00it/s]
Thread: 22: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 249.86it/s]
Thread: 0:  95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████       | 19/20 [00:00<00:00, 120.98it/s]
Thread: 24: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 166.67it/s]
Thread: 4:  95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████       | 19/20 [00:00<00:00, 114.46it/s]
Thread: 5:  95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████       | 19/20 [00:00<00:00, 124.99it/s]
Thread: 1: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 90.09it/s]
Extracting type: non_cells
Saving to: H:\cellfinder_data_test\output\points\non_cells
Thread: 5: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 13/13 [00:00<00:00, 270.82it/s]
Thread: 8: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 294.11it/s]
Thread: 7: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11/11 [00:00<00:00, 305.54it/s]
Thread: 2: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 307.68it/s]
Thread: 0: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 18/18 [00:00<00:00, 310.35it/s]
Thread: 10: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 285.73it/s]
Thread: 9: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:00<00:00, 300.01it/s]
Thread: 14:   0%|                                                                                                                                                    | 0/4 [00:00<?, ?it/s]
Thread: 3: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:00<00:00, 312.51it/s]
Thread: 1: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 17/17 [00:00<00:00, 314.83it/s]
Thread: 4: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 14/14 [00:00<00:00, 318.19it/s]
Thread: 14: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 266.69it/s]
Thread: 11: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 291.66it/s]
Thread: 13: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 277.78it/s]
Thread: 12: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 300.01it/s]
Thread: 15: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 272.73it/s]

Thread: 17: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 166.61it/s]
Saving yaml file to use for training
Closing window
Finished! You may now annotate more datasets, or go straight to training

**Log file**
Please attach the cellfinder log file (e.g. `output/cellfinder_2019-12-17_13-29-46.log`)

**Screenshots**
![error capture](https://user-images.githubusercontent.com/72720700/97426022-d7491800-194d-11eb-850e-d324507b07e5.JPG)

**Desktop (please complete the following information):**
 - OS: [e.g. Linux, Windows, MacOS]
 - Version [e.g. 18.04]
- Hardware specs [e.g. 128GB RAM, Xeon 4114 CPU]

**Additional context**
there no data on the two folders and i can continue. hope for your answer!

**Comment by cindy12-gao** [comment]
@adamltyson

**Comment by adamltyson** [comment]
Hi @cindy12-gao, would you mind:
* Checking that there are no files in the `cells` and `non_cells` directories? They're very small files, and sometimes file browsers don't show them in summaries
* Sending me the `curated_cells.xml` file
* Repeating the same process, but with the `cell_classification.xml` file rather than the `cells.xml` file? If it's the demo data, you should get this if you run cellfinder to completion

Thanks

P.S. You don't need to @ me, I get emails for every issue raised in this repo :)

**Comment by cindy12-gao** [comment]
thank you! first, i`m sure the two folders are empty. 

second[curated_cells.txt](https://github.com/brainglobe/cellfinder/files/5451426/curated_cells.txt)
third there is no cell_classification.xml file ,because if i ran the order of classification, there is error. the log as follows. so i ran --no-classification . above all .i used the demo data.
[classfication error.txt](https://github.com/brainglobe/cellfinder/files/5451439/classfication.error.txt)
[cellfinder_2020-10-28_19-11-18.log](https://github.com/brainglobe/cellfinder/files/5451443/cellfinder_2020-10-28_19-11-18.log)

**Comment by cindy12-gao** [comment]
ps, if i ignore the empty folders and continue the proceedure, it will can`t find 0 image from these two folders

**Comment by adamltyson** [comment]
Thanks.

I'm not sure what's going on with the curation interface, but I think the classification model might not be downloaded properly (leading to the error).

Could you:
* Delete the directory containing the classification model (it will be in your home directory, in a hidden folder called `.cellfinder`. You can delete the whole `.cellfinder` directory
* Retry classification (a new model file should download)

**Comment by cindy12-gao** [comment]
i`ve delete this folder and ran the order, and it did run the downloading file- resnet50_tv. but it seems like will spend a lot of time to download.

**Comment by cindy12-gao** [comment]
![8c1508d18bfac80a14379c3a2d27e98](https://user-images.githubusercontent.com/72720700/97521952-9565b380-19d9-11eb-8449-56572ff95006.jpg)

**Comment by cindy12-gao** [comment]
i`ve tried the order again, the cell_classification.xml file can be generated, but after training process, the folders cells and non-cells are still empty

**Comment by azzhu** [comment]
**I have the same problem...**

**Comment by adamltyson** [comment]
Hi @cindy12-gao, @azzhu. Sorry about this, I found the bug.

Could you try installing the new version of cellfinder (`pip install cellfinder==0.4.5`) and trying again?

**Comment by adamltyson** [comment]
You might see an error like `ValueError: could not broadcast input array from shape (3,3) into shape (2,2)`, but this can be ignored.

**Comment by cindy12-gao** [comment]
thank you! the problem has been solved!
