### ISSUE TITLE
Cellfinder crashes during/after registration due to out of memory

### ISSUE THREAD

**Issue by larsrollik** [brainglobe/cellfinder#157]
**Conditions:**

- Cellfinder as installed on SWC HPC
- SLURM server job with 200GB memory allocation
- Registration with 10µm atlas

**Observation:**
- Last log entry is start of affine registration
- Job gets killed by SLURM due to out of memory
- Same dataset ran successfully with 25µm atlas registration

**Comment by adamltyson** [comment]
Hi @larsrollik, sorry for the delay.

I just tried brainreg on the SWC cluster, and it all ran fine with 80GB memory assigned. Do you still have the logs, and your sbatch file?

**Comment by adamltyson** [comment]
@larsrollik I'm closing this, as cellfinder (& brainreg) seem to be working fine across different machines. If you can reproduce, feel free to reopen.
