### ISSUE TITLE
how to show the detected results and the raw signal data together?

### ISSUE THREAD

**Issue by cindy12-gao** [brainglobe/cellfinder#159]
**Describe the bug**
i want to show the the detected results-cell.xml folder on the raw data rather than the downsampled channel.

**To Reproduce**
![image](https://user-images.githubusercontent.com/72720700/104169783-1231f680-543b-11eb-87f4-b055aa137592.png)

Please enter full details of how to reproduce this bug.

**Expected behavior**

**Log file**
Please attach the cellfinder log file (e.g. `output/cellfinder_2019-12-17_13-29-46.log`)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Linux, Windows, MacOS]
 - Version [e.g. 18.04]
- Hardware specs [e.g. 128GB RAM, Xeon 4114 CPU]

**Additional context**

**Comment by adamltyson** [comment]
Hi,

If you want to visualise the classified cells, see the instructions [here](https://docs.brainglobe.info/cellfinder/tutorial/visualising-the-results).

If you want to visualise another xml file (such as the detected, but not classified cells), then you will need to write your own script to do so. I can't provide support for every custom visualisation that users may require, but something like this may help you get started:

```python
import napari
from napari.utils.io import magic_imread

from imlib.general.system import get_sorted_file_paths
from imlib.IO.cells import cells_xml_to_df
from imlib.cells.cells import Cell


IMAGE_FILES = "/path/to/raw/data/"
CELLS_FILE = "/path/to/classified_cells.xml"


def cells_df_as_np(cells_df, new_order=[2, 1, 0], type_column="type"):
    cells_df = cells_df.drop(columns=[type_column])
    cells = cells_df[cells_df.columns[new_order]]
    cells = cells.to_numpy()
    return cells


def get_cell_arrays(cells_file):
    df = cells_xml_to_df(cells_file)

    non_cells = df[df["type"] == Cell.UNKNOWN]
    cells = df[df["type"] == Cell.CELL]

    cells = cells_df_as_np(cells)
    non_cells = cells_df_as_np(non_cells)
    return cells, non_cells


img_paths = get_sorted_file_paths(IMAGE_FILES, file_extension=".tif")
raw_image = magic_imread(img_paths, use_dask=True, stack=True)

cells, non_cells = get_cell_arrays(CELLS_FILE)

with napari.gui_qt():
    v = napari.Viewer()
    v.add_image(raw_image, name="Full res signal")
    v.add_points(
        non_cells,
        size=20,
        n_dimensional=True,
        opacity=0.8,
        symbol="ring",
        name="Non Cells",
    )
    v.add_points(
        cells,
        size=20,
        n_dimensional=True,
        opacity=0.8,
        symbol="ring",
        name="Cells",
    )
```
