### ISSUE TITLE
Cellfinder crashing with Quadro RTX5000

### ISSUE THREAD

**Issue by atranvan** [brainglobe/cellfinder#162]
cellfinder crashes after starting to run inference, computer shuts down. I tried reinstalling in new environment, crash happens at same stage

Desktop:
- OS: Windows 10
- cellfinder 0.4.8 (full package list attached) [package-list.txt](https://github.com/brainglobe/cellfinder/files/6101530/package-list.txt)
- Hardware specs: 32 GB RAM, Xeon Silver 4114 2.2GHz, Nvidia Quadro RTX5000, 16GB

Please attach the cellfinder log file
[cellfinder_2021-03-06_13-28-25.log](https://github.com/brainglobe/cellfinder/files/6101529/cellfinder_2021-03-06_13-28-25.log)

**Comment by adamltyson** [comment]
@atranvan I haven't seen any more reports of issues with specific GPUs. Is this still an issue? If not, I'll close this.

**Comment by atranvan** [comment]
Hi @adamltyson,

as far as I know we could never fix this - but I no longer have access to the machine, if anything @ederancz may be able to provide any further updates.

**Comment by ederancz** [comment]
feel free to close @adamltyson
