### ISSUE TITLE
Cellfinder stuck with GeForce GTX 1060

### ISSUE THREAD

**Issue by atranvan** [brainglobe/cellfinder#163]
cellfinder stays stuck after starting the running inference step. The graphics card is not in the list of tested ones though

Desktop:

    OS: Ubuntu 20.04
    cellfinder 0.4.8 (full package list attached)[package-list.txt](https://github.com/brainglobe/cellfinder/files/6101581/package-list.txt)

    Hardware specs: 62 GB RAM, Intel i7-8700K CPU @ 3.70GHz, GeForce GTX 1060 6GB

Please attach the cellfinder log file
[cellfinder_2021-03-04_11-00-55.log](https://github.com/brainglobe/cellfinder/files/6101584/cellfinder_2021-03-04_11-00-55.log)

**Comment by adamltyson** [comment]
@atranvan I haven't seen any more reports of issues with specific GPUs. Is this still an issue? If not, I'll close this.
