### ISSUE TITLE
[Feature] CPUVendor awareness.

### ISSUE THREAD

**Issue by SWC-RichardB** [brainglobe/cellfinder#168]
The underlying MKL functions check the vendor of the CPU; If the returned result is anything other than GenuineIntel (IE;AuthenticAMD), then instruction sets are limited to SSE2.

If Cellfinder itself performs a CPUVendor check, then it could apply alternative libraries and functions; For example, setting MKL to a debug mode (export MKL_DEBUG_CPU_TYPE=5), or calling an alternative to MKL (such as openblas).

**Comment by adamltyson** [comment]
Closing this. If users need to improve performance, we'll leave it up to them to either set these variables, or install/compile their own versions of numpy etc.

Thanks for raising @SWC-RichardB :)
