### ISSUE TITLE
Cellfinder on partial brain acquisitions

### ISSUE THREAD

**Issue by jesusdpa1** [brainglobe/cellfinder#170]
Hi!

We are trying to process our partial brain acquisitions through the cellfinder brainreg pipeline. When doing so we see not that precise results on the registration. Are there any constraints on the usage of the pipeline regarding the datasets? i.e: full clear brain using lightsheet? 

Thanks!

**Comment by adamltyson** [comment]
Unfortunately, at the moment cellfinder (and brainreg) requires whole-brain datasets. You've seen https://github.com/brainglobe/brainreg/issues/6, and that's as far as we've got. Supporting brain sub-volumes shouldn't be difficult, I just haven't had the time yet. Lots of people are asking about it, so it is a priority.

**Comment by adamltyson** [comment]
Keeping this issue open. The [data requirements](https://docs.brainglobe.info/cellfinder/user-guide/data-requirements) should be easier to find, and perhaps an FAQ could be helpful.

**Comment by adamltyson** [comment]
Emphasized the link to the data requirements: a33be0c111eb70d08ffa63cc02632e3e25e855bc

This is still an open issue, but needs to be implemented in [brainreg](https://github.com/brainglobe/brainreg/issues/6).
