### ISSUE TITLE
interoperability with abc4d

### ISSUE THREAD

**Issue by valeriabonapersona** [brainglobe/cellfinder#178]
Following out zoom talk, here a description of what's needed. 

- function to be able to save data of each sample as a .npy
- each row is a cell
- columns are the following variables (in this order): 1) anterior/posterior coordinate, 2) superior/inferior coordinate, 3) right/left coordinate, 4) atlas id (numeric). 
- the coordinates are intended in atlas space. 

Thank you very much :)

**Comment by adamltyson** [comment]
This is added in 6bb7952528c0e358f1463f1bd6c54c8d17a9ee97.

Could you test this file to see if it works? It's as above, and the coordinates are in microns (as cellfinder supports different atlas resolutions).

[abc4d.npy](https://www.dropbox.com/s/ltq5kz1w56qirq7/abc4d.npy?dl=1)

**Comment by adamltyson** [comment]
Hi @valeriabonapersona - would you mind checking whether this works so I can merge?

**Comment by valeriabonapersona** [comment]
Hi! Sorry, I missed the previous. I get very weird id values once I import it in R. I tried to look on the brainglobe API (https://brainglobe.info/atlas-api), but the Allen Mouse Brain Atlas page is missing. Could you please direct me to the atlas you are using so I can check whether it's a mistake on my side?

**Comment by adamltyson** [comment]
The atlas ID values are from the latest version of the CCF. Here's the list of structures from the BrainGlobe Atlas API - [structures.csv](https://github.com/brainglobe/cellfinder/files/6509922/structures.csv). Do these make sense?

**Comment by valeriabonapersona** [comment]
The atlas IDs get messed up in the .npy file (i.e. not consistent with structure.csv). Could you please try to save it as a character string? Thank you :)

**Comment by adamltyson** [comment]
Sure. I'll have to save all the data as strings though. I don't think numpy arrays can have mixed data types.

**Comment by valeriabonapersona** [comment]
Lovely, thank you!

**Comment by adamltyson** [comment]
I think storing as a string isn't necessary. For some reason I was converting to 16bit, I think this was messing up some of the very high numbers in the Allen atlas. I've [changed this to `unit32`](https://github.com/brainglobe/cellfinder/commit/cdae7ebed098b007a8cea7485a2c367b099b387d), could you test this file?

[abc4d.npy](https://www.dropbox.com/s/ltq5kz1w56qirq7/abc4d.npy?dl=0)

**Comment by valeriabonapersona** [comment]
It still didn't work, but I tried to re-save from python in different ways, and this is what worked: 

np.save('output.npy', <arrayname>.astype(np.float64))

FYI: 1) The file needs to be saved in 64bits (R works only in 64). 2) The numbers need to be in floats (R does weird things with the integers).

For the rest, the file works perfect! 
Thank you very much :)

**Comment by adamltyson** [comment]
Great. I've updated the export function to `np.float64` (8181d290e08a3dfbe7d1c2d4cfdd9853b55b1354), so all should be good now. This will be in the next version of cellfinder.
