### ISSUE TITLE
[BUG] Issue on cell detection cellfinder v0.4.15 vs cellfinder v0.4.3

### ISSUE THREAD

**Issue by Marilynb24** [brainglobe/cellfinder#181]
**Describe the bug**
Cell detection seems to have some troubles. No cells were found on result visualization with napari and the summary file only displays few cells, which does not correspond to cells observed on images and in the summary file previously obtained with cellfinder v0.4.3.

**To Reproduce**
conda create -n cellfinder_0.4.15 python=3.8		# create env
conda activate cellfinder_0.4.15					# activate env

#Enhance GPU for deep learning
conda install cudatoolkit=11                 # install cudatoolkit 
conda install cudnn -c conda-forge 	# - install cudnn -8.1.0.77

#cellfinder installation 
pip install cellfinder ==0.4.15	       # cellfinder install tensorflow 2.4.1 and cellfinder version 0.4.15	

#test tensorflow installation 
python
>>>import tensorflow as tf
>>> tf.test.is_gpu_available()               #Return True
>>> quit()

# run cellfinder
cellfinder -s test_brain/ch00 -b test_brain/ch01 -o test_brain/output -v 5 2 2 --orientation psl --atlas allen_mouse_10um --start -plane 1000 --end-plane 1500
# Test on image file download on cellfinder website

**Expected behavior**
Considering images and results obtained with older version of cellfinder, cell detection should count more cells.

**Log file**
[cellfinder_2021-05-05_14-28-50.log](https://github.com/brainglobe/cellfinder/files/6439781/cellfinder_2021-05-05_14-28-50.log)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Version 18.04 LTS
- Hardware specs [e.g. 256GB RAM, Xeon E5-2667 v3 (3.20 GHz) CPU, NVIDIA Quadro P5000 12 Gb]

**Additional context**
For example we found 2560 cells in retrosplenial area (vp l5) with cellfinder v0.4.3 and 7 cells with cellfinder v0.4.15.

**Comment by adamltyson** [comment]
Hi, thanks for raising this, it's a bug I missed that only affects certain datasets. Could you try updating cellfinder-core (`pip install cellfinder-core --upgrade`) to see if this fixes the problem?

**Comment by Marilynb24** [comment]
Thanks for your answer. I tried the cellfinder-core update and now cell detection looks fine with cellfinder v0.4.15.

**Comment by adamltyson** [comment]
Excellent. Thanks for letting me know!
