### ISSUE TITLE
[BUG] cell candidate detection failing with cellfinder 0.4.15

### ISSUE THREAD

**Issue by atranvan** [brainglobe/cellfinder#182]
**Describe the bug**

Detecting cell candidates fails with error: 

```
2021-05-13 10:07:36 AM - INFO - MainProcess main.py:118 - Detecting cell candidates
Traceback (most recent call last):
  File "/camp/home/tranvaa/.conda/envs/cellfinder_env2/bin/cellfinder", line 8, in <module>
    sys.exit(main())
  File "/camp/home/tranvaa/.conda/envs/cellfinder_env2/lib/python3.8/site-packages/cellfinder/main.py", line 88, in main
    run_all(args, what_to_run, atlas)
  File "/camp/home/tranvaa/.conda/envs/cellfinder_env2/lib/python3.8/site-packages/cellfinder/main.py", line 120, in run_all
    signal_array = read_with_dask(
  File "/camp/home/tranvaa/.conda/envs/cellfinder_env2/lib/python3.8/site-packages/cellfinder_core/tools/IO.py", line 38, in read_with_dask
    shape, dtype = get_tiff_meta(filenames[0])
IndexError: list index out of range
```

**To Reproduce**
conda create -n cellfinder_env2 python=3.8
conda activate cellfinder_env2
pip install cellfinder
conda install cudatoolkit=11.0
conda install cudnn -c conda-forge

running on a HPC cluster

**Expected behavior**
inference going ahead (the same data gets processed fine with cellfinder 0.4.8)

**Log file**
[cellfinder_2021-05-13_10-07-07.log](https://github.com/brainglobe/cellfinder/files/6471563/cellfinder_2021-05-13_10-07-07.log)

**Additional context**

I get the same error with 3 datasets that ran fine with 0.4.8 with same parameters
I get the same error regardless of whether registration is performed in the same run or not

**Comment by adamltyson** [comment]
Ah, sorry. I think the functionality to load text files pointing to images has gone.

**Comment by atranvan** [comment]
ah I see, thanks, it seems to be running! The registration was still working which got me extra confused, is that likely to also change in brainreg in future versions? Also, is file naming format putatively an issue (our data is labeled under the format section_physicalsection_opticalsection.tif e.g. section_001_01.tif)?

**Comment by adamltyson** [comment]
Yep, the two steps load the data differently, which is why it worked for one, and not the other. If using the text files is useful, I can fix that. I'm trying to simplify the software, but I don't want to take away any features that people use.

The file naming should be fine. Cellfinder uses [natural sorting](https://en.wikipedia.org/wiki/Natural_sort_order) rather than alphabetical, so it should be ok. If there are any problems, let me know and I try to fix it.

**Comment by adamltyson** [comment]
FYI @atranvan, loading from a text file is fixed again. `pip install cellfinder-core -U` should fix it.
