### ISSUE TITLE
[BUG] Registering Failed 

### ISSUE THREAD

**Issue by Newtstein** [brainglobe/cellfinder#185]
**Describe the bug**
INFO:root:Registering
2021-07-28 14:55:15 PM - INFO - MainProcess run.py:56 - Registering
INFO:root:Starting affine registration
2021-07-28 14:55:15 PM - INFO - MainProcess run.py:76 - Starting affine registration
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/imlib/general/system.py", line 282, in safe_execute_command
    cmd, stdout=log_file, stderr=error_file, shell=True
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/brainreg/bin/nifty_reg/osX/reg_aladin -ln 6 -lp 5 -flo /Users/andyhuang/Downloads/brainreg_output/niftyreg/brain_filtered.nii -ref /Users/andyhuang/Downloads/brainreg_output/niftyreg/downsampled_filtered.nii -aff /Users/andyhuang/Downloads/brainreg_output/niftyreg/affine_matrix.txt -res /Users/andyhuang/Downloads/brainreg_output/niftyreg/affine_registered_atlas_brain.nii -omp 4' died with <Signals.SIGABRT: 6>.

**To Reproduce**
I saw a similar issue already posted but the solution is not working (#144). I'm currently only using the test data (not my own) and continue to receive this error. However, an output file is created. My input: (DREADDs) andyhuang@Andys-MacBook-Pro-2 ~ % brainreg /Users/andyhuang/Downloads/test_brain /Users/andyhuang/Downloads/brainreg_output -v 50 40 40  --orientation psl --atlas allen_mouse_50um

**Expected Behaviour**
INFO - MainProcess cli.py:230 - Finished. Total time taken: 0:00:29.15 (from the tutorial)

**Log file**
[brainreg_2021-07-28_14-51-00.log](https://github.com/brainglobe/cellfinder/files/6895891/brainreg_2021-07-28_14-51-00.log)
[brainreg_2021-07-28_14-55-10.log](https://github.com/brainglobe/cellfinder/files/6895894/brainreg_2021-07-28_14-55-10.log)
[brainreg_2021-07-28_14-54-38.log](https://github.com/brainglobe/cellfinder/files/6895895/brainreg_2021-07-28_14-54-38.log)

**Screenshots**

(base) andyhuang@Andys-MacBook-Pro-2 ~ % conda activate DREADDs
(DREADDs) andyhuang@Andys-MacBook-Pro-2 ~ % brainreg /Users/andyhuang/Downloads/test_brain /Users/andyhuang/Downloads/brainreg_output -v 50 40 40  --orientation psl --atlas allen_mouse_50um
INFO:root:Starting logging
2021-07-28 14:55:10 PM - INFO - MainProcess fancylog.py:279 - Starting logging
INFO:root:Not logging multiple processes
2021-07-28 14:55:10 PM - INFO - MainProcess fancylog.py:280 - Not logging multiple processes
INFO:root:Starting registration
2021-07-28 14:55:10 PM - INFO - MainProcess cli.py:197 - Starting registration
allen mouse atlas (res. 50um)
From: http://www.brain-map.org (Wang et al 2020, https://doi.org/10.1016/j.cell.2020.04.007 )
DEBUG:root:Determining the maximum number of CPU cores to use
DEBUG:root:Number of CPU cores available is: 4
DEBUG:root:Setting number of processes to: 4
INFO:root:Loading raw image data
2021-07-28 14:55:11 PM - INFO - MainProcess main.py:48 - Loading raw image data
DEBUG:root:Data type is: directory of files
DEBUG:root:Determining the maximum number of CPU cores to use
DEBUG:root:Number of CPU cores available is: 4
DEBUG:root:Setting number of processes to: 4
Loading images: 100%|████████████████████████████████████████████████| 66/66 [00:00<00:00, 183.90plane/s]
Loading images: 100%|████████████████████████████████████████████████| 68/68 [00:00<00:00, 186.45plane/s]
Loading images: 100%|████████████████████████████████████████████████| 68/68 [00:00<00:00, 186.44plane/s]
Loading images: 100%|████████████████████████████████████████████████| 68/68 [00:00<00:00, 185.87plane/s]
filtering: 100%|███████████████████████████████████████████████████| 228/228 [00:01<00:00, 177.49plane/s]
filtering: 100%|███████████████████████████████████████████████████| 217/217 [00:00<00:00, 325.17plane/s]
INFO:root:Registering
2021-07-28 14:55:15 PM - INFO - MainProcess run.py:56 - Registering
INFO:root:Starting affine registration
2021-07-28 14:55:15 PM - INFO - MainProcess run.py:76 - Starting affine registration
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/imlib/general/system.py", line 282, in safe_execute_command
    cmd, stdout=log_file, stderr=error_file, shell=True
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/brainreg/bin/nifty_reg/osX/reg_aladin -ln 6 -lp 5 -flo /Users/andyhuang/Downloads/brainreg_output/niftyreg/brain_filtered.nii -ref /Users/andyhuang/Downloads/brainreg_output/niftyreg/downsampled_filtered.nii -aff /Users/andyhuang/Downloads/brainreg_output/niftyreg/affine_matrix.txt -res /Users/andyhuang/Downloads/brainreg_output/niftyreg/affine_registered_atlas_brain.nii -omp 4' died with <Signals.SIGABRT: 6>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/brainreg/backend/niftyreg/registration.py", line 76, in register_affine
    self.paths.affine_error_path,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/imlib/general/system.py", line 307, in safe_execute_command
    cmd,
imlib.general.system.SafeExecuteCommandError: 
-------------------------
Process failed:
 dyld: Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/brainreg/bin/nifty_reg/osX/reg_aladin
  Reason: image not found
-------------------------

-------------------------
please read the logs at /Users/andyhuang/Downloads/brainreg_output/niftyreg/affine.log and /Users/andyhuang/Downloads/brainreg_output/niftyreg/affine.err
-------------------------
command: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/brainreg/bin/nifty_reg/osX/reg_aladin -ln 6 -lp 5 -flo /Users/andyhuang/Downloads/brainreg_output/niftyreg/brain_filtered.nii -ref /Users/andyhuang/Downloads/brainreg_output/niftyreg/downsampled_filtered.nii -aff /Users/andyhuang/Downloads/brainreg_output/niftyreg/affine_matrix.txt -res /Users/andyhuang/Downloads/brainreg_output/niftyreg/affine_registered_atlas_brain.nii -omp 4
-------------------------

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/brainreg", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/brainreg/cli.py", line 210, in main
    debug=args.debug,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/brainreg/main.py", line 79, in main
    debug=debug,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/brainreg/backend/niftyreg/run.py", line 77, in run_niftyreg
    brain_reg.register_affine()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/brainreg/backend/niftyreg/registration.py", line 80, in register_affine
    "Affine registration failed; {}".format(err)
brainreg.backend.niftyreg.registration.RegistrationError: Affine registration failed; 
-------------------------
Process failed:
 dyld: Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/brainreg/bin/nifty_reg/osX/reg_aladin
  Reason: image not found
-------------------------

-------------------------
please read the logs at /Users/andyhuang/Downloads/brainreg_output/niftyreg/affine.log and /Users/andyhuang/Downloads/brainreg_output/niftyreg/affine.err
-------------------------
command: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/brainreg/bin/nifty_reg/osX/reg_aladin -ln 6 -lp 5 -flo /Users/andyhuang/Downloads/brainreg_output/niftyreg/brain_filtered.nii -ref /Users/andyhuang/Downloads/brainreg_output/niftyreg/downsampled_filtered.nii -aff /Users/andyhuang/Downloads/brainreg_output/niftyreg/affine_matrix.txt -res /Users/andyhuang/Downloads/brainreg_output/niftyreg/affine_registered_atlas_brain.nii -omp 4

**Additional Context**
@adamltyson
Thank you so much for your time!

**Comment by adamltyson** [comment]
Hi @Newtstein, unfortunately we don't support the registration on macOS. It is usually possible to get it to work, but it's not trivial. Do you have access to a Windows/Linux machine?

**Comment by Newtstein** [comment]
Hey @adamltyson, thanks so much for the immediate reply! That makes total sense, so I acquired a Windows machine and everything worked with the sample data set!
 
**Describe the Bug**
I'm very new to coding so please forgive me if this is a silly question, but I was wondering if there was a way to register an image like the one I attached? It's a slice of the cerebellum along the sagittal plane. Please let me know what information I need to provide for you to better understand the question. I tried doing it and received this error: 

**Screenshot**
Loading images:  33%|███████              | 1/3 [00:00<00:00,  4.54plane/s]
Loading images:  33%|███████              | 1/3 [00:00<00:00,  3.81plane/s]
Loading images:  33%|███████              | 1/3 [00:00<00:00,  4.44plane/s]
Loading images:   0%|                             | 0/3 [00:00<?, ?plane/s]concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "c:\users\tracing\appdata\local\programs\python\python37\lib\concurrent\futures\process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "c:\users\tracing\appdata\local\programs\python\python37\lib\site-packages\imio\load.py", line 459, in load_from_paths_sequence
    volume[:, :, i] = img
ValueError: could not broadcast input array from shape (3789,3788) into shape (3789,3789)
"""

**Additional Context**
Thank you in advance! 

<img width="725" alt="Screen Shot 2021-07-30 at 8 37 54 PM" src="https://user-images.githubusercontent.com/87092669/127723248-9ecd0fb9-c947-45c1-b061-11267bf6fb89.png">

[Sample Slice.zip](https://github.com/brainglobe/cellfinder/files/6910419/Sample.Slice.zip)

**Comment by adamltyson** [comment]
Unfortunately, brainreg is designed for 3D, whole-brain datasets, so that isn't enough data to work with. Check out [this forum post](https://forum.image.sc/t/comparison-of-some-tools-for-brain-slice-to-atlas-registration/43260) for links to some 2D registration tools.

**Comment by adamltyson** [comment]
Closing this issue, let me know if I can be of help with anything @Newtstein.

**Comment by Newtstein** [comment]
Yes, thank you so much for providing that forum post for 2D registration! You have been a tremendous help. Thanks again and have a wonderful week @adamltyson
