### ISSUE TITLE
'No cells detected' line when positives have been classified

### ISSUE THREAD

**Issue by samclothier** [brainglobe/cellfinder#190]
Hi,

I am getting a line saying that no cells have been detected:
```
MainProcess main.py:219 - No cells detected, skipping         main.py:219
```

The figure generation step is being skipped by cellfinder, so I don't get any figures in the output directory. 

I attach the log file with the cell_classification.xml file.
[cellfinder_log.txt](https://github.com/brainglobe/cellfinder/files/7806865/cellfinder_log.txt)
[cell_classification.txt](https://github.com/brainglobe/cellfinder/files/7806891/cell_classification.txt)

The output directory contains the .log and .json files, and the analysis, points, and registration folders.

**Comment by adamltyson** [comment]
Hi Sam,

Sorry I forgot this issue has already been fixed in a newer version of cellfinder. If you upgrade (`pip install cellfinder -U`) this should be sorted.

Let me know if you have any other issues
Adam

**Comment by samclothier** [comment]
Thanks Adam, this appears to have worked. Should I expect the heatmap image alone in the figures directory?

**Comment by adamltyson** [comment]
Yep, that's the only one.
