### ISSUE TITLE
[Feature]Could you please supply you .npy file in your ouput from you example data

### ISSUE THREAD

**Issue by AmaranthCao** [brainglobe/cellfinder#201]
Hello,
I wonder could you please supply the .npy file of your output, because you know, you exampled data is too large to test. So I am writing to ask if you could supply your output file directly, so that I can test your package directly on brainrender.

Thanks a lot!

**Comment by adamltyson** [comment]
Hey @AmaranthCao, [here is the data from the brainrender paper](https://github.com/brainglobe/brainrender/blob/master/paper/data/cell-detect-paper-cells.npy). Hope this helps!
