### ISSUE TITLE
[BUG] cellfinder interacts badly with multiprocessing_logging on Python 3.9.13

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/cellfinder#207]
@dstansby Nothing has changed with cellfinder, is this something to do with the actions?

**Comment by paddyroddy** [comment]
It appears to be failing with this
```
Traceback (most recent call last):
File "D:\a\cellfinder\cellfinder\.tox\py39-\lib\site-packages\multiprocessing_logging.py", line 81, in _receive
  record = self.queue.get(timeout=0.2)
File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\multiprocessing\queues.py", line 113, in get
  if not self._poll(timeout):
File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\multiprocessing\connection.py", line 260, in poll
  self._check_closed()
OSError: [WinError 6] The handle is invalid
File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\multiprocessing\connection.py", line 335, in _poll
  return bool(wait([self], timeout))
File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\multiprocessing\connection.py", line 888, in wait
  ov.cancel()
File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\multiprocessing\connection.py", line 335, in _poll
  return bool(wait([self], timeout))
File "D:\a\cellfinder\cellfinder\.tox\py39-\lib\site-packages\multiprocessing_logging.py", line 81, in _receive
  record = self.queue.get(timeout=0.2)
OSError: [WinError 6] The handle is invalid
OSError: handle is closed
```
which I think is related to https://stackoverflow.com/questions/40108816/python-running-as-windows-service-oserror-winerror-6-the-handle-is-invalid

I'm a bit confused, though, as I don't see any use of `subprocess` or `multiprocessing`. Any idea @alessandrofelder ?

**Comment by adamltyson** [comment]
There's multiprocessing in `cellfinder-core`?

**Comment by dstansby** [comment]
Taking a look into this - will post thoughts/investigations as I do them.

Comparing a run that passed (https://github.com/brainglobe/cellfinder/runs/6576037299) and one that didn't (https://github.com/brainglobe/cellfinder/runs/6613252660) the only differences in dependencies installed are:

- pysygnal 0.3.4 > 0.3.5
- hsluv 5.0.2 > 5.0.3
- dask 2022.5.0 > 2022.5.1

The `cellfinder-core` versions are the same, so this seems to be a sporadic issue. I think the diagnosis of it being a multiprocessing issue coming from `cellfinder-core` is correct.

**Comment by dstansby** [comment]
In #209 the tests failed on Linux, so this is an OS-agnostic issue.

**Comment by dstansby** [comment]
Looking down the Python 3.9.13 changelog, I *think* this issue is caused by https://github.com/python/cpython/pull/31913 interacting badly with `multiprocessing-logging`. I think this next step to take here is raise an issue at https://github.com/jruere/multiprocessing-logging/issues - I don't have time to do that with an example right now, but hopefully this helps for debugging purposes.

**Comment by paddyroddy** [comment]
> Looking down the Python 3.9.13 changelog, I _think_ this issue is caused by [python/cpython#31913](https://github.com/python/cpython/pull/31913) interacting badly with `multiprocessing-logging`. I think this next step to take here is raise an issue at https://github.com/jruere/multiprocessing-logging/issues - I don't have time to do that with an example right now, but hopefully this helps for further debugging purposes.

Nice work 🙌 I ran out of time to look into this last week

**Comment by dstansby** [comment]
I've reported this upstream: https://github.com/jruere/multiprocessing-logging/issues/56

**Comment by dstansby** [comment]
I don't have time to check properley this afternoon, but this might also be fixed by closing the worker pool properley in `cellfinder-core`: https://github.com/brainglobe/cellfinder-core/pull/53/commits/21f33bba57901a81c90ad0baf45aa43d02ceefc9

**Comment by dstansby** [comment]
Another update, I can reproduce this with the following small example:

```python
from fancylog import fancylog
from multiprocessing import Pool
import cellfinder_core


if __name__ == "__main__":
    fancylog.start_logging(
    '.',
    cellfinder_core,
    log_header="LOG",
)
    with Pool(8) as worker_pool:
        pass
```

**Comment by adamltyson** [comment]
`multiprocessing-logging` has this issue on many Python versions now, with no sign of a fix. In the newest version of [fancylog](https://github.com/adamltyson/fancylog) I've changed the default behaviour to not use `multiprocessing-logging` so this issue is resolved for now. When `multiprocessing-logging` is fixed, we can re-enable the logging in this package.
