### ISSUE TITLE
[BUG] Napari and brainreg-segment dependencies not fetched

### ISSUE THREAD

**Issue by willGraham01** [brainglobe/cellfinder#245]
**Describe the bug**

`napari` is a hard dependency of this package but it is only included as an optional dependency.
Similarly, `brainreg-segment` is also required for the `cellfinder_curate_new` script to be executed, but is not included as a dependency.

**To Reproduce**
```sh
$ mamba create -n cf-cli python=3.9
$ pip install cellfinder
$ cellfinder_curate_new
Traceback (most recent call last):
  File "/home/ccaegra/mambaforge/envs/cellfinder-cli/bin/cellfinder_curate_new", line 5, in <module>
    from cellfinder.train.curation import main
  File "/home/ccaegra/mambaforge/envs/cellfinder-cli/lib/python3.9/site-packages/cellfinder/train/curation.py", line 4, in <module>
    import napari
ModuleNotFoundError: No module named 'napari'

```

**Expected behaviour**
`napari` and `brainreg-segment` should be hard dependencies.

**Computer used (please complete the following information):**

- OS: Ubuntu 22.04

**Comment by adamltyson** [comment]
I think actually these should be removed. They are included for backwards compatibility, but I think (TBC) they are not needed anymore.

**Comment by willGraham01** [comment]
> I think actually these should be removed. They are included for backwards compatibility, but I think (TBC) they are not needed anymore.

These = the `cellfinder_curate` and `cellfinder_curate_new` CLI entry points right? 

The corresponding functions / scripts should also be removed along with them too I presume?

**Comment by adamltyson** [comment]
Yes and yes. I'm not 100% but I think they aren't used. They certainly aren't documented anymore.

**Comment by willGraham01** [comment]
> Yes and yes. I'm not 100% but I think they aren't used. They certainly aren't documented anymore.

Cool, I'll modify #247 with these changes so they happen at the same time as the switch to pyproject.toml
