### ISSUE TITLE
[BUG] CLI scripts raise errors due to missing functions.

### ISSUE THREAD

**Issue by willGraham01** [brainglobe/cellfinder#246]
**Describe the bug**

The `cellfinder_curate_new` and `cellfinder_curate` CLI options that come with the package raise errors when invoked, due to missing functions.

**To Reproduce**
Install the package into a clean environment, then (to circumnavigate #245) install `napari` and `brainreg-segment`.
Then run
```sh
$ cellfinder_curate_new
Traceback (most recent call last):
  File "/home/ccaegra/mambaforge/envs/test/bin/cellfinder_curate_new", line 5, in <module>
    from cellfinder.train.curation import main
  File "/home/ccaegra/mambaforge/envs/test/lib/python3.9/site-packages/cellfinder/train/curation.py", line 12, in <module>
    from napari.utils.io import magic_imread
ImportError: cannot import name 'magic_imread' from 'napari.utils.io' (/home/ccaegra/mambaforge/envs/test/lib/python3.9/site-packages/napari/utils/io.py)

```

There is an additional issue with the fact that the same script(s) also attempt to import
```python
napari_cellfinder.cellfinder
```

which doesn't exist. Presumably this should be `cellfinder-napari` or `cellfinder-core`.

**Expected behaviour**
No error should be produced - the missing import must be resolved.

**Comment by adamltyson** [comment]
See https://github.com/brainglobe/cellfinder/issues/245#issuecomment-1682264300
