### ISSUE TITLE
Run cellfinder-napari tests in CI

### ISSUE THREAD

**Issue by alessandrofelder** [brainglobe/cellfinder#277]
See e.g. https://github.com/brainglobe/cellfinder-core/actions/runs/5545953658/jobs/10125615811 CI failure, which should be fixed.

**Comment by adamltyson** [comment]
cellfinder-core and cellfinder-napari have now been merged in this repo, so I think this issue can be closed. @alessandrofelder feeel free to reopen if I've misunderstood.
