### ISSUE TITLE
[BUG] Tests failing with tensorflow 2.12.0

### ISSUE THREAD

**Issue by dstansby** [brainglobe/cellfinder#293]
The release of tensorflow 2.12.0 is causing some of our tests to fail. See e.g. https://github.com/brainglobe/cellfinder-core/actions/runs/4503578523/jobs/7926945458.

I don't have time to investigate now, so I'll pin to `tensorflow<2.12.0` in dependencies for now.

**Comment by adamltyson** [comment]
Closing now we've moved to torch, this issue no longer exists :tada:

**Comment by dstansby** [comment]
🥳
