### ISSUE TITLE
[Feature] Refactor curation widget to use `magicgui` widgets

### ISSUE THREAD

**Issue by alessandrofelder** [brainglobe/cellfinder#313]
**Is your feature request related to a problem? Please describe.**
The curation widget is currently pure Qt, and does not take advantage of `magicgui`.
This adds a maintenance burden for the developers.

**Describe the solution you'd like**
The curation widget should consist of `magicgui` widgets as far as possible.

**Describe alternatives you've considered**
None.

**Additional context**
I may be lacking the understanding as to why the Curation Widget does not currently use any `magicgui` widgets.

**Comment by adamltyson** [comment]
@alessandrofelder do you still think that not using magicgui is a maintenance burden, considering all of our new plugins are mostly pure Qt?

**Comment by alessandrofelder** [comment]
Nope, very much changed my mind on this one 😆 at least, I think the explicitness and fine control Qt is worth the maintenance, and may even make maintanance easier (Qt learning curve permitting).
