### ISSUE TITLE
Add full set of smoke tests

### ISSUE THREAD

**Issue by dstansby** [brainglobe/cellfinder#317]
This is related to https://github.com/brainglobe/cellfinder/issues/338, but I'm opening this a subset of the tests we want to add. As a first round of tests we should add a set of smoke tests, that check that the code is running. Once this is done we can then use these as a base to create regression tests to check that the code is running correctly. The goal of this issue is to get code coverage as close to 100% as possible.

**Comment by adamltyson** [comment]
Coverage is currently at 90%. This issue was transferred from the `cellfinder-napari` repo when they were merged, so I'm going to close this issue as I think it would be better to have issues about specific areas to test.
