### ISSUE TITLE
Should default values for voxel size be removed?

### ISSUE THREAD

**Issue by dstansby** [brainglobe/cellfinder#320]
I'm running through the `cellfinder-napari` guide and [there's a section](https://docs.brainglobe.info/cellfinder-napari/user-guide/cell-detection/parameters-to-set) that says that selecting the voxel size is mandatory and no defaults are listed. Currently there are defaults set in the widget however:
![Screenshot 2022-04-06 at 09 14 26](https://user-images.githubusercontent.com/6197628/161928236-377f8007-b698-4751-8aaf-56cccb1ca33f.png)

Should we:
- Remove the defaults in the widget, and force the user to choose a value?
- Update the docs to list the default values, but still recommend the values are updated by the user?

**Comment by adamltyson** [comment]
Closing as I think the current status (defaults that are often close to the users actual data) seem to work ok.
