### ISSUE TITLE
Import HTML headers from brainglobe-utils

### ISSUE THREAD

**Issue by alessandrofelder** [brainglobe/cellfinder#327]
Don't think this is a priority right now, but it feels weird to me to hardcode html into Python fstrings. Would there be a better solution?

**Comment by adamltyson** [comment]
@alessandrofelder these [headers are now in `brainglobe-utils`](https://github.com/brainglobe/brainglobe-utils/blob/main/brainglobe_utils/qtpy/logo.py), so should this issue now be to import them from that package, rather than duplicate in cellfinder?

**Comment by alessandrofelder** [comment]
Yes!

**Comment by adamltyson** [comment]
I guess it should be anything with a napari plugin? @alessandrofelder

So:
- cellfinder
- brainreg
- brainglobe-segmentation
- brainglobe-registration (although that will be up to @IgorTatarnikov)
- brainrender-napari (up to @alessandrofelder)

**Comment by K-Meech** [comment]
Currently, the `cellfinder` header links to [one of the documentation pages for cellfinder](https://github.com/brainglobe/cellfinder/blob/main/cellfinder/napari/utils.py#L17C13-L17C97). The `brainglobe-utils` header currently [only supports linking to tutorials](https://github.com/brainglobe/brainglobe-utils/blob/main/brainglobe_utils/qtpy/logo.py#L16). Would you be happy to link to the [cellfinder tutorial](https://brainglobe.info/tutorials/cellfinder-detection.html) instead? Or would you prefer the documentation link to be kept?

**Comment by adamltyson** [comment]
I think it should probably support either/and. We won't always have a tutorial corresponding to a plugin.

**Comment by K-Meech** [comment]
The cellfinder [`train`](https://github.com/brainglobe/cellfinder/blob/de73504d42646a68314245f7b96010d8a5642e8f/cellfinder/napari/train/train.py#L43) and [`detect`](https://github.com/brainglobe/cellfinder/blob/de73504d42646a68314245f7b96010d8a5642e8f/cellfinder/napari/detect/detect.py#L42) widgets are still using `magicgui`, rather than `qtpy` directly like many of the other BrainGlobe widgets. This makes it difficult to re-use the brainglobe header in a consistent way. Is it fine if I remove use of `magicgui` in these widgets?

**Comment by adamltyson** [comment]
> The cellfinder [`train`](https://github.com/brainglobe/cellfinder/blob/de73504d42646a68314245f7b96010d8a5642e8f/cellfinder/napari/train/train.py#L43) and [`detect`](https://github.com/brainglobe/cellfinder/blob/de73504d42646a68314245f7b96010d8a5642e8f/cellfinder/napari/detect/detect.py#L42) widgets are still using `magicgui`, rather than `qtpy` directly like many of the other BrainGlobe widgets. This makes it difficult to re-use the brainglobe header in a consistent way. Is it fine if I remove use of `magicgui` in these widgets?

I don't see why not. Unless it's a lot of work to do so (then feel free to not bother!).

**Comment by alessandrofelder** [comment]
It would be nice to get the tests to pass with the new `macos-latest` runners first - see https://brainglobe.zulipchat.com/#narrow/stream/408841-development/topic/Mac.20CI.20has.20started.20failing.20due.20to.20new.20ARM.20runners.20.28I.20think.29.

Apart from that I think we're good to go.

(There's some major updates to cellfinder coming up, but that can be a separate, bigger, new release?)

**Comment by adamltyson** [comment]
Yeah I would say release now, but if there's any large changes included, make a note so we can advertise

**Comment by adamltyson** [comment]
Closing this as the header is now imported from `brainglobe-utils`
