### ISSUE TITLE
Developer docs

### ISSUE THREAD

**Issue by alessandrofelder** [brainglobe/cellfinder#332]
We should have developer docs.
- [ ] decide on place where we keep developer docs for this.
- [ ] this place should contain all docstrings (auto-generated)
- [ ] this place should also document any underlying design decisions (what things do we test here and which do we leave to napari/cellfinder-core? How/when do we validate inputs? What kind of error message/progress bar widgets do we use, ...) we made during [the familiarisation/strategisation milestone](https://github.com/brainglobe/cellfinder-napari/milestone/1) (and beyond!).

**Comment by adamltyson** [comment]
I think this is now done with https://brainglobe.info/community/developers/index.html (although of course more detail can be added). Still outstanding is:
* #286 
* #291 
* #333
