### ISSUE TITLE
Add an initial round of tests

### ISSUE THREAD

**Issue by alessandrofelder** [brainglobe/cellfinder#338]
Currently we only have[ a placeholder test.](https://github.com/brainglobe/cellfinder-napari/blob/641f729a915cebe30a437f7a553e4eec3cb8d3b6/cellfinder_napari/_tests/test_cellfinder_napari.py)

Test for cellfinder-napari should focus on UI testing and workflow testing (actual computations done and tested in cellfinder-core)
Workshop of 19th January by napari devs should give us some additional guidance/tips to write tests.

Still need to decide on what exactly test contents will be.

**Comment by adamltyson** [comment]
There are a reasonable number of tests in this (now-merged) repo, so I'm going to close this in favour of the other test-related issues.
