### ISSUE TITLE
[Feature] Use uint16 for cell candidate detection when signal_array is small, to save memory

### ISSUE THREAD

**Issue by alessandrofelder** [brainglobe/cellfinder#386]
**Is your feature request related to a problem? Please describe.**
As part of fixing #383 cellfinder memory use for candidate detection will need to increase.
We could try to increase only when we need to, by limiting the increase to only cases where it's possible 

**Describe the solution you'd like**
`signal_array` in `detect` should only be cast to uint32 if it's theoretically possible.
I believe `signal_array`s with fewer than ~~`2**15`~~ `2**17` total pixels cannot have more than `2**16` structures, because the worst case is a 3D checkerboard of cells marked as pixels (half of the pixels labelled as cell).

**Comment by adamltyson** [comment]
> I believe signal_arrays with fewer than 2**15 total pixels cannot have more than 2**16 structs, because the worst case is a 3D checkerboard of cells marked as pixels (half of the pixels labelled as cell).

This wouldn't happen much in real use though right? Unless I'm missing something, $\sqrt{2^{15}} \approx 180 \times 180$. 180 x 180 is a fairly small image.

**Comment by alessandrofelder** [comment]
We can reopen this if memory becomes an issue, I guess. Closing for now.
