### ISSUE TITLE
[BUG] Cellfinder seems to get stuck on structure splitting in some situations?

### ISSUE THREAD

**Issue by alessandrofelder** [brainglobe/cellfinder#409]
**Describe the bug**
On a large dataset, somewhere in the final parts of the candidate detection code, cellfinde might be getting stuck.

**To Reproduce**
I am yet to reproduce.

**Expected behaviour**
- at least, good user feedback (a progress bar)
- certainty that cellfinder is not stuck

**Log file**
[brainglobe_workflows_2024-04-27_17-46-03.log](https://github.com/brainglobe/cellfinder/files/15175237/brainglobe_workflows_2024-04-27_17-46-03.log)

**Screenshots**
n/a

**Computer used (please complete the following information):**
18 core desktop with a 3090 ti graphics card (attached log file), reportedly reproduced on a 32 core desktop too.

> I've mostly run brainmapper on an 18 core desktop with a 3090 ti graphics card and it typically takes 2-7 hrs to process 100 planes.
> 
> Last Saturday I attempted to run a whole cfos brain on a desktop equipped with a 32 core threadripper and a 3090 graphics card but it's been stuck for the last 3 days at the terminal output below:
> 
> NumbaTypeSafetyWarning: unsafe cast from int64 to uint64. Precision may be lost.
>   return d[key]
> 
> Please also find attached a log file where I tried to run a whole cfos brain on the 18 core desktop and it got stuck in the same place.

**Additional context**
n/a

**Comment by alessandrofelder** [comment]
This is not reproducible on the same dataset with the same settings on latest `main` - presumably thanks to the improvements contributed in #398 . 

I suggest
* we make a new release soon, and a note about this in release notes/cellfinder blogpost
* keep this issue open until we find the root cause and cover it with a test to future proof (if possible, i.e. if we can reproduce on GH actions runners)

**Comment by adamltyson** [comment]
Should we actually just close it? If you can't reproduce it on main, doesn't that mean we won't find the root cause (unless you spend lots of time digging into 1.1.3)?

**Comment by alessandrofelder** [comment]
OK, let's close this for now.

If anyone this issue before cellfinder 1.2 is released (next week), please try installing from the `main` branch 

```bash
pip install git+https://github.com/brainglobe/cellfinder
```

If you can still reproduce the issue on `main`, please let us know by re-opening this issue 🙏
