### ISSUE TITLE
[Feature] Simple (non training) curation interface

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/cellfinder#43]
`cellfinder_curate` should have an option to not just save the toggled/confirmed cells, but edit (or make a new) `cell_classification.xml`. In case the classification is broadly correct, but users want to manually edit a couple of cells.

**Comment by chrytsi** [comment]
It would be awesome to have the option of manually adding cells that were already missed at the stage of candidate detection to an existing xml file.

**Comment by adamltyson** [comment]
@chrytsi is this taken care of with [`cellfinder_view`](https://docs.cellfinder.info/user-guide/visualisation) or is there still missing functionality?
