### ISSUE TITLE
[Feature] GUI for training data: toggle flip all selected cells into same category in one step

### ISSUE THREAD

**Issue by larsrollik** [brainglobe/cellfinder#60]
**Is your feature request related to a problem? Please describe.**
When selecting many cells/non-cells in same area (maybe dense spacing), a multi-select does not mean application of the same category assignment, but will result in each individual selection being toggled into the inverse. It is not possible to select a group that should be classified as cells *or* non-cells and do so in one step. - It takes very long to toggle one category individually (item by item) and then confirm the area instead of all at once.

**Describe the solution you'd like**
It would be convenient to select a group and on toggle move them all into one label category, so that at most two flips are required to move all of them into the desired label.

**Describe alternatives you've considered**
Allow toggle only category-specific, e.g. when "cells" is selected, "toggle" will only act on these.

**Additional context**
.

**Comment by larsrollik** [comment]
Might relate to issue #24 .

**Comment by adamltyson** [comment]
Yep, this needs to be added. Thanks @larsrollik

**Comment by adamltyson** [comment]
This functionality is now in the [cellfinder napari plugin](https://docs.brainglobe.info/cellfinder-napari/user-guide/training-data-generation).
