### ISSUE TITLE
[Feature] GUI/tool for assessing the quality of cellfinder steps and choosing the right model

### ISSUE THREAD

**Issue by stephenlenzi** [brainglobe/cellfinder#99]
**Is your feature request related to a problem? Please describe.**

I am trying to establish a workflow for cellfinder and I find it can be difficult to have an overview of the quality of cell classification and even though cellfinder is fast it can still take a long time to assess how well a given set of parameters performs. 

Currently I run cellfinder using the defaults, then I curate the outcome and retrain and rerun and then find out that my new network was not sufficient). This can take a long time.

**Describe the solution you'd like**
I think it would be useful to have a GUI that allows for comparison of outcomes on the fly on reduced datasets giving the user control of pre-preprocessing steps and allowing on the fly classification using different trained models for classification.

**Comment by adamltyson** [comment]
This is pretty much the new [cellfinder napari plugin](https://github.com/brainglobe/cellfinder-napari). Feel free to open an issue there if there are features missing.
